### ISSUE TITLE
JSDoc

### ISSUE THREAD

**Issue by Default4152** [dominicvogl/project-jamming#1]
Great! I really like your usage of JSDoc throughout the project - it really helps with clarifying important parts of your code. If you liked JSDoc, I would recommend checking out http://documentation.js.org if you haven't yet!

**Comment by dominicvogl** [comment]
I didn't know documentation.js.org yet. Thank you for this!
I think a good documentation helps you is someone else wants to look at your code or myself in future. And with PHPstorm it is very easy to do that ;-)
